defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  autocreate_indexes: false
  raise_not_found_error: true

development:
  <<: *defaults
  database: nsagentbackend

test:
  <<: *defaults
  database: nsagentbackend_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>

